sudo: required

dist: trusty

addons:
  sonarqube: true

jdk:
  - oraclejdk8

before_install: 
  - if [ $TRAVIS_OS_NAME == "linux" ]; then 
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - wget -O os.deb http://oscript.io/downloads/latest/deb
  - sudo apt-get install mono-complete mono-devel
  - sudo dpkg -i os.deb; sudo apt install -f
  - sudo oscript /usr/share/oscript/lib/opm/src/opm.os install opm
  - wget https://ci.appveyor.com/api/projects/dmpas/onescript/artifacts/oscript.zip?branch=feature/codestat --output-document oscript.zip
  - sudo unzip -o oscript.zip -d /usr/share/oscript/bin
  - oscript

install: 
  - sudo oscript /usr/share/oscript/lib/opm/src/opm.os install

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - ./travis.sh 
